asyncapi: 2.6.0
info:
  title: Echo
  version: 0.1.0
channels:
  audio_raw:
    description: This topic contains unprocessed audio meta
    subscribe:
      message:
        $ref: '#/components/messages/AudioRaw'
    publish:
      message:
        $ref: '#/components/messages/AudioRaw'
  audio_preprocessed:
    description: This topic contains preprocessed audio meta
    subscribe:
      message:
        $ref: '#/components/messages/AudioPreprocessed'
    publish:
      message:
        $ref: '#/components/messages/AudioPreprocessed'
  audio_transcribed_tg:
    description: This topic contains transcribed audio for Telegram bot
    subscribe:
      message:
        $ref: '#/components/messages/AudioTranscribedTg'
    publish:
      message:
        $ref: '#/components/messages/AudioTranscribedTg'

components:
  messages:
    AudioRaw:
      name: audio_raw
      title: AudioRaw
      description: Raw audio metadata
      contentType: application/json
      payload:
        type: object
        properties:
          meta:
            $ref: '#/components/schemas/MessageMeta'
          content:
            $ref: '#/components/schemas/AudioRaw'
    AudioPreprocessed:
      name: audio_preprocessed
      title: AudioPreprocessed
      description: Preprocessed audio metadata
      contentType: application/json
      payload:
        type: object
        properties:
          meta:
            $ref: '#/components/schemas/MessageMeta'
          content:
            $ref: '#/components/schemas/AudioPreprocessed'
    AudioTranscribedTg:
      name: audio_transcribed_tg
      title: AudioTranscribedTg
      description: Transcribed audio metadata
      contentType: application/json
      payload:
        type: object
        properties:
          meta:
            $ref: '#/components/schemas/MessageMeta'
          content:
            $ref: '#/components/schemas/AudioTranscribed'

  schemas:
    AudioRaw:
      type: object
      properties:
        id:
          type: string
          description: Message UUID
        user_id:
          type: string
          description: User ID
        duration:
          type: integer
          description: Duration of audio in milliseconds
        size:
          type: integer
          description: Size of audio in bytes
        format:
          type: string
          enum: ["ogg", "oga"]
          description: Audio format
        sample_rate:
          type: integer
          description: Audio sample rate
        channels:
          type: integer
          enum: [1, 2]
          description: Audio channels
        source:
          type: string
          enum: ["tg"]
          description: Source of audio (telegram bot, web api, etc)
        timestamp:
          type: integer
          description: Audio timestamp in UNIX nano format
      required:
        - id
        - user_id
        - format
        - source
      example:
        id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        user_id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        duration: 4300
        size: 23014
        format: "ogg"
        sample_rate: 48000
        channels: 1
        source: "tg"
        timestamp: 1720780001234567890
    AudioPreprocessed:
      type: object
      properties:
        id:
          type: string
          description: Message UUID
        user_id:
          type: string
          description: User ID
        duration:
          type: integer
          description: Duration of audio in milliseconds
        size:
          type: integer
          description: Size of audio in bytes
        channels:
          type: integer
          enum: [1, 2]
          description: Audio channels
        source:
          type: string
          enum: ["tg"]
          description: Source of audio (telegram bot, web api, etc)
        timestamp:
          type: integer
          description: Audio timestamp in UNIX nano format
      required:
        - id
        - user_id
        - source
      example:
        id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        user_id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        duration: 4300
        size: 23014
        channels: 1
        source: "tg"
        timestamp: 1720780001234567890
    AudioTranscribed:
      type: object
      properties:
        id:
          type: string
          description: Message UUID
        user_id:
          type: string
          description: User ID
        transcription:
          type: string
          description: Audio transcription
        timestamp:
          type: integer
          description: Audio timestamp in UNIX nano format
      required:
        - id
        - user_id
        - transcription
      example:
        id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        user_id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        transcription: "Some transcribed text"
        timestamp: 1720780001234567890
    Error:
      type: object
      properties:
        code:
          type: integer
          enum: [ 1 ]
          description: Error code
        message:
          type: string
          description: Error message
      required:
        - code
        - message
      example:
        code: 1
        message: "Transcription failed due to unreadable audio"
    MessageMeta:
      type: object
      properties:
        status:
          type: string
          enum: ["ok", "error"]
        error:
          $ref: '#/components/schemas/Error'
      required:
        - status
      examples:
        - status: "ok"
        - status: "error"
          error:
            code: 1
            message: "Transcription failed due to unreadable audio"